# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import audit_pb2 as proto_dot_audit__pb2


class AuditServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogActivity = channel.unary_unary(
                '/audit.AuditService/LogActivity',
                request_serializer=proto_dot_audit__pb2.LogActivityRequest.SerializeToString,
                response_deserializer=proto_dot_audit__pb2.LogActivityResponse.FromString,
                )
        self.ListAuditLogs = channel.unary_unary(
                '/audit.AuditService/ListAuditLogs',
                request_serializer=proto_dot_audit__pb2.ListAuditLogsRequest.SerializeToString,
                response_deserializer=proto_dot_audit__pb2.ListAuditLogsResponse.FromString,
                )


class AuditServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogActivity(self, request, context):
        """Log an activity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuditLogs(self, request, context):
        """List audit logs (internal/admin usage)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.LogActivity,
                    request_deserializer=proto_dot_audit__pb2.LogActivityRequest.FromString,
                    response_serializer=proto_dot_audit__pb2.LogActivityResponse.SerializeToString,
            ),
            'ListAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditLogs,
                    request_deserializer=proto_dot_audit__pb2.ListAuditLogsRequest.FromString,
                    response_serializer=proto_dot_audit__pb2.ListAuditLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audit.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/audit.AuditService/LogActivity',
            proto_dot_audit__pb2.LogActivityRequest.SerializeToString,
            proto_dot_audit__pb2.LogActivityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/audit.AuditService/ListAuditLogs',
            proto_dot_audit__pb2.ListAuditLogsRequest.SerializeToString,
            proto_dot_audit__pb2.ListAuditLogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
