# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/audit.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/audit.proto\x12\x05\x61udit\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xaf\x01\n\x12LogActivityRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x15\n\rresource_type\x18\x03 \x01(\t\x12\x13\n\x0bresource_id\x18\x04 \x01(\t\x12(\n\x07\x64\x65tails\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x12\n\nip_address\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\"2\n\x13LogActivityResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\"\xe1\x01\n\x08\x41uditLog\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x15\n\rresource_type\x18\x04 \x01(\t\x12\x13\n\x0bresource_id\x18\x05 \x01(\t\x12(\n\x07\x64\x65tails\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x12\n\nip_address\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12.\n\ncreated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xe9\x01\n\x14ListAuditLogsRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x15\n\rresource_type\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12.\n\nstart_date\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06search\x18\t \x01(\t\"F\n\x15ListAuditLogsResponse\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.audit.AuditLog\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xa0\x01\n\x0c\x41uditService\x12\x44\n\x0bLogActivity\x12\x19.audit.LogActivityRequest\x1a\x1a.audit.LogActivityResponse\x12J\n\rListAuditLogs\x12\x1b.audit.ListAuditLogsRequest\x1a\x1c.audit.ListAuditLogsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.audit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGACTIVITYREQUEST']._serialized_start=92
  _globals['_LOGACTIVITYREQUEST']._serialized_end=267
  _globals['_LOGACTIVITYRESPONSE']._serialized_start=269
  _globals['_LOGACTIVITYRESPONSE']._serialized_end=319
  _globals['_AUDITLOG']._serialized_start=322
  _globals['_AUDITLOG']._serialized_end=547
  _globals['_LISTAUDITLOGSREQUEST']._serialized_start=550
  _globals['_LISTAUDITLOGSREQUEST']._serialized_end=783
  _globals['_LISTAUDITLOGSRESPONSE']._serialized_start=785
  _globals['_LISTAUDITLOGSRESPONSE']._serialized_end=855
  _globals['_AUDITSERVICE']._serialized_start=858
  _globals['_AUDITSERVICE']._serialized_end=1018
# @@protoc_insertion_point(module_scope)
