# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import deployment_pb2 as deployment__pb2


class DeploymentServiceStub(object):
    """Deployment Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDeployment = channel.unary_unary(
                '/deployment.DeploymentService/CreateDeployment',
                request_serializer=deployment__pb2.CreateDeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeploymentResponse.FromString,
                )
        self.GetDeployment = channel.unary_unary(
                '/deployment.DeploymentService/GetDeployment',
                request_serializer=deployment__pb2.GetDeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeploymentResponse.FromString,
                )
        self.UpdateDeployment = channel.unary_unary(
                '/deployment.DeploymentService/UpdateDeployment',
                request_serializer=deployment__pb2.UpdateDeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeploymentResponse.FromString,
                )
        self.DeleteDeployment = channel.unary_unary(
                '/deployment.DeploymentService/DeleteDeployment',
                request_serializer=deployment__pb2.DeleteDeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.Empty.FromString,
                )
        self.ListDeployments = channel.unary_unary(
                '/deployment.DeploymentService/ListDeployments',
                request_serializer=deployment__pb2.ListDeploymentsRequest.SerializeToString,
                response_deserializer=deployment__pb2.ListDeploymentsResponse.FromString,
                )
        self.GetDeploymentHistory = channel.unary_unary(
                '/deployment.DeploymentService/GetDeploymentHistory',
                request_serializer=deployment__pb2.GetDeploymentHistoryRequest.SerializeToString,
                response_deserializer=deployment__pb2.ListDeploymentHistoryResponse.FromString,
                )
        self.GetDeploymentHistoryVersion = channel.unary_unary(
                '/deployment.DeploymentService/GetDeploymentHistoryVersion',
                request_serializer=deployment__pb2.GetDeploymentHistoryVersionRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeploymentHistoryResponse.FromString,
                )
        self.AddDeploymentTag = channel.unary_unary(
                '/deployment.DeploymentService/AddDeploymentTag',
                request_serializer=deployment__pb2.AddDeploymentTagRequest.SerializeToString,
                response_deserializer=deployment__pb2.Empty.FromString,
                )
        self.RemoveDeploymentTag = channel.unary_unary(
                '/deployment.DeploymentService/RemoveDeploymentTag',
                request_serializer=deployment__pb2.RemoveDeploymentTagRequest.SerializeToString,
                response_deserializer=deployment__pb2.Empty.FromString,
                )
        self.ListDeploymentTags = channel.unary_unary(
                '/deployment.DeploymentService/ListDeploymentTags',
                request_serializer=deployment__pb2.ListDeploymentTagsRequest.SerializeToString,
                response_deserializer=deployment__pb2.ListDeploymentTagsResponse.FromString,
                )
        self.UpdateCICDStatus = channel.unary_unary(
                '/deployment.DeploymentService/UpdateCICDStatus',
                request_serializer=deployment__pb2.UpdateCICDStatusRequest.SerializeToString,
                response_deserializer=deployment__pb2.Empty.FromString,
                )
        self.GetCICDStatus = channel.unary_unary(
                '/deployment.DeploymentService/GetCICDStatus',
                request_serializer=deployment__pb2.GetCICDStatusRequest.SerializeToString,
                response_deserializer=deployment__pb2.CICDStatusResponse.FromString,
                )
        self.GetDeploymentStats = channel.unary_unary(
                '/deployment.DeploymentService/GetDeploymentStats',
                request_serializer=deployment__pb2.GetDeploymentStatsRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeploymentStatsResponse.FromString,
                )
        self.GetDeploymentCosts = channel.unary_unary(
                '/deployment.DeploymentService/GetDeploymentCosts',
                request_serializer=deployment__pb2.GetDeploymentCostsRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeploymentCostsResponse.FromString,
                )


class DeploymentServiceServicer(object):
    """Deployment Service
    """

    def CreateDeployment(self, request, context):
        """CRUD Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDeployment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeployments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentHistory(self, request, context):
        """Deployment History
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentHistoryVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDeploymentTag(self, request, context):
        """Tags
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDeploymentTag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeploymentTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCICDStatus(self, request, context):
        """CI/CD Status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCICDStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentStats(self, request, context):
        """Statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentCosts(self, request, context):
        """Cost Tracking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeploymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDeployment,
                    request_deserializer=deployment__pb2.CreateDeploymentRequest.FromString,
                    response_serializer=deployment__pb2.DeploymentResponse.SerializeToString,
            ),
            'GetDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeployment,
                    request_deserializer=deployment__pb2.GetDeploymentRequest.FromString,
                    response_serializer=deployment__pb2.DeploymentResponse.SerializeToString,
            ),
            'UpdateDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDeployment,
                    request_deserializer=deployment__pb2.UpdateDeploymentRequest.FromString,
                    response_serializer=deployment__pb2.DeploymentResponse.SerializeToString,
            ),
            'DeleteDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDeployment,
                    request_deserializer=deployment__pb2.DeleteDeploymentRequest.FromString,
                    response_serializer=deployment__pb2.Empty.SerializeToString,
            ),
            'ListDeployments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeployments,
                    request_deserializer=deployment__pb2.ListDeploymentsRequest.FromString,
                    response_serializer=deployment__pb2.ListDeploymentsResponse.SerializeToString,
            ),
            'GetDeploymentHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentHistory,
                    request_deserializer=deployment__pb2.GetDeploymentHistoryRequest.FromString,
                    response_serializer=deployment__pb2.ListDeploymentHistoryResponse.SerializeToString,
            ),
            'GetDeploymentHistoryVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentHistoryVersion,
                    request_deserializer=deployment__pb2.GetDeploymentHistoryVersionRequest.FromString,
                    response_serializer=deployment__pb2.DeploymentHistoryResponse.SerializeToString,
            ),
            'AddDeploymentTag': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDeploymentTag,
                    request_deserializer=deployment__pb2.AddDeploymentTagRequest.FromString,
                    response_serializer=deployment__pb2.Empty.SerializeToString,
            ),
            'RemoveDeploymentTag': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDeploymentTag,
                    request_deserializer=deployment__pb2.RemoveDeploymentTagRequest.FromString,
                    response_serializer=deployment__pb2.Empty.SerializeToString,
            ),
            'ListDeploymentTags': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeploymentTags,
                    request_deserializer=deployment__pb2.ListDeploymentTagsRequest.FromString,
                    response_serializer=deployment__pb2.ListDeploymentTagsResponse.SerializeToString,
            ),
            'UpdateCICDStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCICDStatus,
                    request_deserializer=deployment__pb2.UpdateCICDStatusRequest.FromString,
                    response_serializer=deployment__pb2.Empty.SerializeToString,
            ),
            'GetCICDStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCICDStatus,
                    request_deserializer=deployment__pb2.GetCICDStatusRequest.FromString,
                    response_serializer=deployment__pb2.CICDStatusResponse.SerializeToString,
            ),
            'GetDeploymentStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentStats,
                    request_deserializer=deployment__pb2.GetDeploymentStatsRequest.FromString,
                    response_serializer=deployment__pb2.DeploymentStatsResponse.SerializeToString,
            ),
            'GetDeploymentCosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentCosts,
                    request_deserializer=deployment__pb2.GetDeploymentCostsRequest.FromString,
                    response_serializer=deployment__pb2.DeploymentCostsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deployment.DeploymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeploymentService(object):
    """Deployment Service
    """

    @staticmethod
    def CreateDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/CreateDeployment',
            deployment__pb2.CreateDeploymentRequest.SerializeToString,
            deployment__pb2.DeploymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/GetDeployment',
            deployment__pb2.GetDeploymentRequest.SerializeToString,
            deployment__pb2.DeploymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/UpdateDeployment',
            deployment__pb2.UpdateDeploymentRequest.SerializeToString,
            deployment__pb2.DeploymentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/DeleteDeployment',
            deployment__pb2.DeleteDeploymentRequest.SerializeToString,
            deployment__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDeployments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/ListDeployments',
            deployment__pb2.ListDeploymentsRequest.SerializeToString,
            deployment__pb2.ListDeploymentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeploymentHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/GetDeploymentHistory',
            deployment__pb2.GetDeploymentHistoryRequest.SerializeToString,
            deployment__pb2.ListDeploymentHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeploymentHistoryVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/GetDeploymentHistoryVersion',
            deployment__pb2.GetDeploymentHistoryVersionRequest.SerializeToString,
            deployment__pb2.DeploymentHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDeploymentTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/AddDeploymentTag',
            deployment__pb2.AddDeploymentTagRequest.SerializeToString,
            deployment__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveDeploymentTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/RemoveDeploymentTag',
            deployment__pb2.RemoveDeploymentTagRequest.SerializeToString,
            deployment__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDeploymentTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/ListDeploymentTags',
            deployment__pb2.ListDeploymentTagsRequest.SerializeToString,
            deployment__pb2.ListDeploymentTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCICDStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/UpdateCICDStatus',
            deployment__pb2.UpdateCICDStatusRequest.SerializeToString,
            deployment__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCICDStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/GetCICDStatus',
            deployment__pb2.GetCICDStatusRequest.SerializeToString,
            deployment__pb2.CICDStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeploymentStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/GetDeploymentStats',
            deployment__pb2.GetDeploymentStatsRequest.SerializeToString,
            deployment__pb2.DeploymentStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeploymentCosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deployment.DeploymentService/GetDeploymentCosts',
            deployment__pb2.GetDeploymentCostsRequest.SerializeToString,
            deployment__pb2.DeploymentCostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
