# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import plugin_pb2 as plugin__pb2


class PluginServiceStub(object):
    """Plugin Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadPlugin = channel.unary_unary(
                '/plugin.PluginService/UploadPlugin',
                request_serializer=plugin__pb2.UploadPluginRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginVersionResponse.FromString,
                )
        self.UploadMicroserviceTemplate = channel.unary_unary(
                '/plugin.PluginService/UploadMicroserviceTemplate',
                request_serializer=plugin__pb2.UploadMicroserviceTemplateRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginVersionResponse.FromString,
                )
        self.ListPlugins = channel.unary_unary(
                '/plugin.PluginService/ListPlugins',
                request_serializer=plugin__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=plugin__pb2.ListPluginsResponse.FromString,
                )
        self.GetPlugin = channel.unary_unary(
                '/plugin.PluginService/GetPlugin',
                request_serializer=plugin__pb2.GetPluginRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginResponse.FromString,
                )
        self.DeletePlugin = channel.unary_unary(
                '/plugin.PluginService/DeletePlugin',
                request_serializer=plugin__pb2.DeletePluginRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                )
        self.LockPlugin = channel.unary_unary(
                '/plugin.PluginService/LockPlugin',
                request_serializer=plugin__pb2.LockPluginRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                )
        self.UnlockPlugin = channel.unary_unary(
                '/plugin.PluginService/UnlockPlugin',
                request_serializer=plugin__pb2.UnlockPluginRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                )
        self.ListPluginVersions = channel.unary_unary(
                '/plugin.PluginService/ListPluginVersions',
                request_serializer=plugin__pb2.ListPluginVersionsRequest.SerializeToString,
                response_deserializer=plugin__pb2.ListPluginVersionsResponse.FromString,
                )
        self.GetPluginVersion = channel.unary_unary(
                '/plugin.PluginService/GetPluginVersion',
                request_serializer=plugin__pb2.GetPluginVersionRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginVersionResponse.FromString,
                )
        self.RequestPluginAccess = channel.unary_unary(
                '/plugin.PluginService/RequestPluginAccess',
                request_serializer=plugin__pb2.RequestPluginAccessRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginAccessRequestResponse.FromString,
                )
        self.GrantPluginAccess = channel.unary_unary(
                '/plugin.PluginService/GrantPluginAccess',
                request_serializer=plugin__pb2.GrantPluginAccessRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginAccessResponse.FromString,
                )
        self.RejectPluginAccess = channel.unary_unary(
                '/plugin.PluginService/RejectPluginAccess',
                request_serializer=plugin__pb2.RejectPluginAccessRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                )
        self.RevokePluginAccess = channel.unary_unary(
                '/plugin.PluginService/RevokePluginAccess',
                request_serializer=plugin__pb2.RevokePluginAccessRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                )
        self.RestorePluginAccess = channel.unary_unary(
                '/plugin.PluginService/RestorePluginAccess',
                request_serializer=plugin__pb2.RestorePluginAccessRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                )
        self.ListAccessRequests = channel.unary_unary(
                '/plugin.PluginService/ListAccessRequests',
                request_serializer=plugin__pb2.ListAccessRequestsRequest.SerializeToString,
                response_deserializer=plugin__pb2.ListAccessRequestsResponse.FromString,
                )
        self.ListAccessGrants = channel.unary_unary(
                '/plugin.PluginService/ListAccessGrants',
                request_serializer=plugin__pb2.ListAccessGrantsRequest.SerializeToString,
                response_deserializer=plugin__pb2.ListAccessGrantsResponse.FromString,
                )
        self.ProvisionPlugin = channel.unary_unary(
                '/plugin.PluginService/ProvisionPlugin',
                request_serializer=plugin__pb2.ProvisionPluginRequest.SerializeToString,
                response_deserializer=plugin__pb2.ProvisionResponse.FromString,
                )
        self.GetJob = channel.unary_unary(
                '/plugin.PluginService/GetJob',
                request_serializer=plugin__pb2.GetJobRequest.SerializeToString,
                response_deserializer=plugin__pb2.JobResponse.FromString,
                )
        self.ListJobs = channel.unary_unary(
                '/plugin.PluginService/ListJobs',
                request_serializer=plugin__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=plugin__pb2.ListJobsResponse.FromString,
                )
        self.GetJobLogs = channel.unary_unary(
                '/plugin.PluginService/GetJobLogs',
                request_serializer=plugin__pb2.GetJobLogsRequest.SerializeToString,
                response_deserializer=plugin__pb2.JobLogsResponse.FromString,
                )
        self.CancelJob = channel.unary_unary(
                '/plugin.PluginService/CancelJob',
                request_serializer=plugin__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                )
        self.DeleteJob = channel.unary_unary(
                '/plugin.PluginService/DeleteJob',
                request_serializer=plugin__pb2.DeleteJobRequest.SerializeToString,
                response_deserializer=plugin__pb2.Empty.FromString,
                )


class PluginServiceServicer(object):
    """Plugin Service
    """

    def UploadPlugin(self, request, context):
        """Plugin Upload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadMicroserviceTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """Plugin CRUD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPluginVersions(self, request, context):
        """Plugin Versions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPluginVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPluginAccess(self, request, context):
        """Plugin Access Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantPluginAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectPluginAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokePluginAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestorePluginAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessGrants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvisionPlugin(self, request, context):
        """Plugin Provisioning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPlugin,
                    request_deserializer=plugin__pb2.UploadPluginRequest.FromString,
                    response_serializer=plugin__pb2.PluginVersionResponse.SerializeToString,
            ),
            'UploadMicroserviceTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadMicroserviceTemplate,
                    request_deserializer=plugin__pb2.UploadMicroserviceTemplateRequest.FromString,
                    response_serializer=plugin__pb2.PluginVersionResponse.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=plugin__pb2.ListPluginsRequest.FromString,
                    response_serializer=plugin__pb2.ListPluginsResponse.SerializeToString,
            ),
            'GetPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlugin,
                    request_deserializer=plugin__pb2.GetPluginRequest.FromString,
                    response_serializer=plugin__pb2.PluginResponse.SerializeToString,
            ),
            'DeletePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlugin,
                    request_deserializer=plugin__pb2.DeletePluginRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'LockPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.LockPlugin,
                    request_deserializer=plugin__pb2.LockPluginRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'UnlockPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockPlugin,
                    request_deserializer=plugin__pb2.UnlockPluginRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'ListPluginVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPluginVersions,
                    request_deserializer=plugin__pb2.ListPluginVersionsRequest.FromString,
                    response_serializer=plugin__pb2.ListPluginVersionsResponse.SerializeToString,
            ),
            'GetPluginVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginVersion,
                    request_deserializer=plugin__pb2.GetPluginVersionRequest.FromString,
                    response_serializer=plugin__pb2.PluginVersionResponse.SerializeToString,
            ),
            'RequestPluginAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPluginAccess,
                    request_deserializer=plugin__pb2.RequestPluginAccessRequest.FromString,
                    response_serializer=plugin__pb2.PluginAccessRequestResponse.SerializeToString,
            ),
            'GrantPluginAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantPluginAccess,
                    request_deserializer=plugin__pb2.GrantPluginAccessRequest.FromString,
                    response_serializer=plugin__pb2.PluginAccessResponse.SerializeToString,
            ),
            'RejectPluginAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectPluginAccess,
                    request_deserializer=plugin__pb2.RejectPluginAccessRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'RevokePluginAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokePluginAccess,
                    request_deserializer=plugin__pb2.RevokePluginAccessRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'RestorePluginAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RestorePluginAccess,
                    request_deserializer=plugin__pb2.RestorePluginAccessRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'ListAccessRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessRequests,
                    request_deserializer=plugin__pb2.ListAccessRequestsRequest.FromString,
                    response_serializer=plugin__pb2.ListAccessRequestsResponse.SerializeToString,
            ),
            'ListAccessGrants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessGrants,
                    request_deserializer=plugin__pb2.ListAccessGrantsRequest.FromString,
                    response_serializer=plugin__pb2.ListAccessGrantsResponse.SerializeToString,
            ),
            'ProvisionPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvisionPlugin,
                    request_deserializer=plugin__pb2.ProvisionPluginRequest.FromString,
                    response_serializer=plugin__pb2.ProvisionResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=plugin__pb2.GetJobRequest.FromString,
                    response_serializer=plugin__pb2.JobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=plugin__pb2.ListJobsRequest.FromString,
                    response_serializer=plugin__pb2.ListJobsResponse.SerializeToString,
            ),
            'GetJobLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobLogs,
                    request_deserializer=plugin__pb2.GetJobLogsRequest.FromString,
                    response_serializer=plugin__pb2.JobLogsResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=plugin__pb2.CancelJobRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
            'DeleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteJob,
                    request_deserializer=plugin__pb2.DeleteJobRequest.FromString,
                    response_serializer=plugin__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plugin.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PluginService(object):
    """Plugin Service
    """

    @staticmethod
    def UploadPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/UploadPlugin',
            plugin__pb2.UploadPluginRequest.SerializeToString,
            plugin__pb2.PluginVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadMicroserviceTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/UploadMicroserviceTemplate',
            plugin__pb2.UploadMicroserviceTemplateRequest.SerializeToString,
            plugin__pb2.PluginVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/ListPlugins',
            plugin__pb2.ListPluginsRequest.SerializeToString,
            plugin__pb2.ListPluginsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/GetPlugin',
            plugin__pb2.GetPluginRequest.SerializeToString,
            plugin__pb2.PluginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/DeletePlugin',
            plugin__pb2.DeletePluginRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LockPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/LockPlugin',
            plugin__pb2.LockPluginRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnlockPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/UnlockPlugin',
            plugin__pb2.UnlockPluginRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPluginVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/ListPluginVersions',
            plugin__pb2.ListPluginVersionsRequest.SerializeToString,
            plugin__pb2.ListPluginVersionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPluginVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/GetPluginVersion',
            plugin__pb2.GetPluginVersionRequest.SerializeToString,
            plugin__pb2.PluginVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestPluginAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/RequestPluginAccess',
            plugin__pb2.RequestPluginAccessRequest.SerializeToString,
            plugin__pb2.PluginAccessRequestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GrantPluginAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/GrantPluginAccess',
            plugin__pb2.GrantPluginAccessRequest.SerializeToString,
            plugin__pb2.PluginAccessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RejectPluginAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/RejectPluginAccess',
            plugin__pb2.RejectPluginAccessRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokePluginAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/RevokePluginAccess',
            plugin__pb2.RevokePluginAccessRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestorePluginAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/RestorePluginAccess',
            plugin__pb2.RestorePluginAccessRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAccessRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/ListAccessRequests',
            plugin__pb2.ListAccessRequestsRequest.SerializeToString,
            plugin__pb2.ListAccessRequestsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAccessGrants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/ListAccessGrants',
            plugin__pb2.ListAccessGrantsRequest.SerializeToString,
            plugin__pb2.ListAccessGrantsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProvisionPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/ProvisionPlugin',
            plugin__pb2.ProvisionPluginRequest.SerializeToString,
            plugin__pb2.ProvisionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/GetJob',
            plugin__pb2.GetJobRequest.SerializeToString,
            plugin__pb2.JobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/ListJobs',
            plugin__pb2.ListJobsRequest.SerializeToString,
            plugin__pb2.ListJobsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/GetJobLogs',
            plugin__pb2.GetJobLogsRequest.SerializeToString,
            plugin__pb2.JobLogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/CancelJob',
            plugin__pb2.CancelJobRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plugin.PluginService/DeleteJob',
            plugin__pb2.DeleteJobRequest.SerializeToString,
            plugin__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
