# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import notification_pb2 as notification__pb2


class NotificationServiceStub(object):
    """Notification Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNotification = channel.unary_unary(
                '/notification.NotificationService/CreateNotification',
                request_serializer=notification__pb2.CreateNotificationRequest.SerializeToString,
                response_deserializer=notification__pb2.NotificationResponse.FromString,
                )
        self.GetNotification = channel.unary_unary(
                '/notification.NotificationService/GetNotification',
                request_serializer=notification__pb2.GetNotificationRequest.SerializeToString,
                response_deserializer=notification__pb2.NotificationResponse.FromString,
                )
        self.ListNotifications = channel.unary_unary(
                '/notification.NotificationService/ListNotifications',
                request_serializer=notification__pb2.ListNotificationsRequest.SerializeToString,
                response_deserializer=notification__pb2.ListNotificationsResponse.FromString,
                )
        self.UpdateNotification = channel.unary_unary(
                '/notification.NotificationService/UpdateNotification',
                request_serializer=notification__pb2.UpdateNotificationRequest.SerializeToString,
                response_deserializer=notification__pb2.NotificationResponse.FromString,
                )
        self.DeleteNotification = channel.unary_unary(
                '/notification.NotificationService/DeleteNotification',
                request_serializer=notification__pb2.DeleteNotificationRequest.SerializeToString,
                response_deserializer=notification__pb2.Empty.FromString,
                )
        self.MarkAsRead = channel.unary_unary(
                '/notification.NotificationService/MarkAsRead',
                request_serializer=notification__pb2.MarkAsReadRequest.SerializeToString,
                response_deserializer=notification__pb2.NotificationResponse.FromString,
                )
        self.MarkAllAsRead = channel.unary_unary(
                '/notification.NotificationService/MarkAllAsRead',
                request_serializer=notification__pb2.MarkAllAsReadRequest.SerializeToString,
                response_deserializer=notification__pb2.Empty.FromString,
                )
        self.GetUnreadCount = channel.unary_unary(
                '/notification.NotificationService/GetUnreadCount',
                request_serializer=notification__pb2.GetUnreadCountRequest.SerializeToString,
                response_deserializer=notification__pb2.UnreadCountResponse.FromString,
                )


class NotificationServiceServicer(object):
    """Notification Service
    """

    def CreateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAsRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAllAsRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnreadCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotification,
                    request_deserializer=notification__pb2.CreateNotificationRequest.FromString,
                    response_serializer=notification__pb2.NotificationResponse.SerializeToString,
            ),
            'GetNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotification,
                    request_deserializer=notification__pb2.GetNotificationRequest.FromString,
                    response_serializer=notification__pb2.NotificationResponse.SerializeToString,
            ),
            'ListNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotifications,
                    request_deserializer=notification__pb2.ListNotificationsRequest.FromString,
                    response_serializer=notification__pb2.ListNotificationsResponse.SerializeToString,
            ),
            'UpdateNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNotification,
                    request_deserializer=notification__pb2.UpdateNotificationRequest.FromString,
                    response_serializer=notification__pb2.NotificationResponse.SerializeToString,
            ),
            'DeleteNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNotification,
                    request_deserializer=notification__pb2.DeleteNotificationRequest.FromString,
                    response_serializer=notification__pb2.Empty.SerializeToString,
            ),
            'MarkAsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAsRead,
                    request_deserializer=notification__pb2.MarkAsReadRequest.FromString,
                    response_serializer=notification__pb2.NotificationResponse.SerializeToString,
            ),
            'MarkAllAsRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAllAsRead,
                    request_deserializer=notification__pb2.MarkAllAsReadRequest.FromString,
                    response_serializer=notification__pb2.Empty.SerializeToString,
            ),
            'GetUnreadCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnreadCount,
                    request_deserializer=notification__pb2.GetUnreadCountRequest.FromString,
                    response_serializer=notification__pb2.UnreadCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Notification Service
    """

    @staticmethod
    def CreateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/CreateNotification',
            notification__pb2.CreateNotificationRequest.SerializeToString,
            notification__pb2.NotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/GetNotification',
            notification__pb2.GetNotificationRequest.SerializeToString,
            notification__pb2.NotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/ListNotifications',
            notification__pb2.ListNotificationsRequest.SerializeToString,
            notification__pb2.ListNotificationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/UpdateNotification',
            notification__pb2.UpdateNotificationRequest.SerializeToString,
            notification__pb2.NotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/DeleteNotification',
            notification__pb2.DeleteNotificationRequest.SerializeToString,
            notification__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MarkAsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/MarkAsRead',
            notification__pb2.MarkAsReadRequest.SerializeToString,
            notification__pb2.NotificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MarkAllAsRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/MarkAllAsRead',
            notification__pb2.MarkAllAsReadRequest.SerializeToString,
            notification__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUnreadCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.NotificationService/GetUnreadCount',
            notification__pb2.GetUnreadCountRequest.SerializeToString,
            notification__pb2.UnreadCountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
