# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import worker_pb2 as worker__pb2


class WorkerServiceStub(object):
    """Worker Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProvisionInfrastructure = channel.unary_unary(
                '/worker.WorkerService/ProvisionInfrastructure',
                request_serializer=worker__pb2.ProvisionInfrastructureRequest.SerializeToString,
                response_deserializer=worker__pb2.TaskResponse.FromString,
                )
        self.DestroyInfrastructure = channel.unary_unary(
                '/worker.WorkerService/DestroyInfrastructure',
                request_serializer=worker__pb2.DestroyInfrastructureRequest.SerializeToString,
                response_deserializer=worker__pb2.TaskResponse.FromString,
                )
        self.ProvisionMicroservice = channel.unary_unary(
                '/worker.WorkerService/ProvisionMicroservice',
                request_serializer=worker__pb2.ProvisionMicroserviceRequest.SerializeToString,
                response_deserializer=worker__pb2.TaskResponse.FromString,
                )
        self.DestroyMicroservice = channel.unary_unary(
                '/worker.WorkerService/DestroyMicroservice',
                request_serializer=worker__pb2.DestroyMicroserviceRequest.SerializeToString,
                response_deserializer=worker__pb2.TaskResponse.FromString,
                )
        self.CleanupStuckDeployments = channel.unary_unary(
                '/worker.WorkerService/CleanupStuckDeployments',
                request_serializer=worker__pb2.Empty.SerializeToString,
                response_deserializer=worker__pb2.TaskResponse.FromString,
                )
        self.CleanupExpiredRefreshTokens = channel.unary_unary(
                '/worker.WorkerService/CleanupExpiredRefreshTokens',
                request_serializer=worker__pb2.Empty.SerializeToString,
                response_deserializer=worker__pb2.TaskResponse.FromString,
                )
        self.PollGitHubActionsStatus = channel.unary_unary(
                '/worker.WorkerService/PollGitHubActionsStatus',
                request_serializer=worker__pb2.Empty.SerializeToString,
                response_deserializer=worker__pb2.TaskResponse.FromString,
                )
        self.ProcessGitHubWebhook = channel.unary_unary(
                '/worker.WorkerService/ProcessGitHubWebhook',
                request_serializer=worker__pb2.ProcessGitHubWebhookRequest.SerializeToString,
                response_deserializer=worker__pb2.ProcessGitHubWebhookResponse.FromString,
                )
        self.GetTaskStatus = channel.unary_unary(
                '/worker.WorkerService/GetTaskStatus',
                request_serializer=worker__pb2.GetTaskStatusRequest.SerializeToString,
                response_deserializer=worker__pb2.TaskStatusResponse.FromString,
                )


class WorkerServiceServicer(object):
    """Worker Service
    """

    def ProvisionInfrastructure(self, request, context):
        """Infrastructure Provisioning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyInfrastructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvisionMicroservice(self, request, context):
        """Microservice Provisioning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyMicroservice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupStuckDeployments(self, request, context):
        """Cleanup Tasks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupExpiredRefreshTokens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollGitHubActionsStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessGitHubWebhook(self, request, context):
        """GitHub Webhooks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Task Status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProvisionInfrastructure': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvisionInfrastructure,
                    request_deserializer=worker__pb2.ProvisionInfrastructureRequest.FromString,
                    response_serializer=worker__pb2.TaskResponse.SerializeToString,
            ),
            'DestroyInfrastructure': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyInfrastructure,
                    request_deserializer=worker__pb2.DestroyInfrastructureRequest.FromString,
                    response_serializer=worker__pb2.TaskResponse.SerializeToString,
            ),
            'ProvisionMicroservice': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvisionMicroservice,
                    request_deserializer=worker__pb2.ProvisionMicroserviceRequest.FromString,
                    response_serializer=worker__pb2.TaskResponse.SerializeToString,
            ),
            'DestroyMicroservice': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyMicroservice,
                    request_deserializer=worker__pb2.DestroyMicroserviceRequest.FromString,
                    response_serializer=worker__pb2.TaskResponse.SerializeToString,
            ),
            'CleanupStuckDeployments': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupStuckDeployments,
                    request_deserializer=worker__pb2.Empty.FromString,
                    response_serializer=worker__pb2.TaskResponse.SerializeToString,
            ),
            'CleanupExpiredRefreshTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupExpiredRefreshTokens,
                    request_deserializer=worker__pb2.Empty.FromString,
                    response_serializer=worker__pb2.TaskResponse.SerializeToString,
            ),
            'PollGitHubActionsStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.PollGitHubActionsStatus,
                    request_deserializer=worker__pb2.Empty.FromString,
                    response_serializer=worker__pb2.TaskResponse.SerializeToString,
            ),
            'ProcessGitHubWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessGitHubWebhook,
                    request_deserializer=worker__pb2.ProcessGitHubWebhookRequest.FromString,
                    response_serializer=worker__pb2.ProcessGitHubWebhookResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=worker__pb2.GetTaskStatusRequest.FromString,
                    response_serializer=worker__pb2.TaskStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Worker Service
    """

    @staticmethod
    def ProvisionInfrastructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/ProvisionInfrastructure',
            worker__pb2.ProvisionInfrastructureRequest.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyInfrastructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/DestroyInfrastructure',
            worker__pb2.DestroyInfrastructureRequest.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProvisionMicroservice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/ProvisionMicroservice',
            worker__pb2.ProvisionMicroserviceRequest.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyMicroservice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/DestroyMicroservice',
            worker__pb2.DestroyMicroserviceRequest.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CleanupStuckDeployments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/CleanupStuckDeployments',
            worker__pb2.Empty.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CleanupExpiredRefreshTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/CleanupExpiredRefreshTokens',
            worker__pb2.Empty.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PollGitHubActionsStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/PollGitHubActionsStatus',
            worker__pb2.Empty.SerializeToString,
            worker__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessGitHubWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/ProcessGitHubWebhook',
            worker__pb2.ProcessGitHubWebhookRequest.SerializeToString,
            worker__pb2.ProcessGitHubWebhookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/worker.WorkerService/GetTaskStatus',
            worker__pb2.GetTaskStatusRequest.SerializeToString,
            worker__pb2.TaskStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
